name: ooc-dev

services:
  client:
    image: orleans-client:development
    pull_policy: build
    build:
      context: .
      dockerfile: ./Client/Dockerfile
      args:
        - Configuration=Release
    environment:
      - Client__ClusteringProvider=development
      - SiloEndpoints__0__HostName=silo
      - SiloEndpoints__0__Port=30000
    depends_on:
      - silo
    stdin_open: true
    tty: true
    deploy:
      replicas: 2

  silo:
    image: orleans-silo:development
    pull_policy: build
    build:
      context: .
      dockerfile: ./Silo/Dockerfile
      args:
        - Configuration=Release
    environment:
      - Silo__ClusteringProvider=development
      - PrimarySilo__HostName=silo
      - PrimarySilo__Port=11111