name: ooc-dev

services:
  client:
    image: orleans-client:development
    build:
      context: .
      dockerfile: .\Client\Dockerfile
      args:
        - Configuration=Release
    env_file:
      - .\Client\.env.development
    environment:
      - Client__ClusteringProvider=development
    depends_on:
      - silo
    stdin_open: true
    tty: true
    deploy:
      replicas: 2

  silo:
    image: orleans-silo:development
    build:
      context: .
      dockerfile: .\Silo\Dockerfile
      args:
        - Configuration=Release
    env_file:
      - .\Silo\.env.development
    environment:
      - Silo__ClusteringProvider=development